trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Desarrollo
  jobs:
  - job: AppBuild
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/'
        api_location: 'api'
        output_location: 'build'
        app_build_command: $(commanddev)
        azure_static_web_apps_api_token: $(deployment_token)


- stage: ValidacionDesarrollo
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation  
    pool: server    
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:   
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          test@test.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'


- stage: Produccion
  jobs:
  - job: AppBuildProduccion
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/'
        api_location: 'api'
        output_location: 'build'
        app_build_command: $(commandprd)
        azure_static_web_apps_api_token: $(deployment_token_prd)